```{r}
rm(list = ls())
Sys.setlocale(locale = "english")
```

```{r functions}
get.category <- function(string, patterns, names) {
  match <- str_extract(tolower(string), patterns)
  index <- which(!is.na(match))
  index <- ifelse(length(index)>0, index, -1)
  if(index == -1){
    return(-1)
  }else{
    return(names[index])
  }
}

View.subset <- function(dataframe,n=10){
  rndm <- runif(n,1,nrow(dataframe))
  View(dataframe[rndm,])
}

concat.as.date <- function(el){
  indices <- c(8,2:6)
  return(paste(el[indices], collapse =  "-"))
}
```

```{r loading_packages}
setwd("D:\\Mohab\\csen1061-project1-traffic-data-analysis")
# Loading librariesinit.dflkjlk
require(dplyr)
require(tidyr)
require(stringr)
require(ggplot2)
require(readr)
require(lubridate)
require(lattice)
require(gplots)
```

```{r reading_data}
# Loading data
df <- read_csv("all-semi-unique.csv")
colnames(df) <- gsub("/", ".", colnames(df))
df <- df %>% mutate(comment = as.character(rd.rp.cm))

# Checking for duplicates of df$commentid
duplicates <- duplicated(df$rd.rp.cmid)
n.duplicates <- sum(duplicates)
percent.duplicates <- n.duplicates/dim(df)[1]
print(percent.duplicates)
# About 65% of the data is duplicated
old.df <- df
df <- df[!duplicates,]
#tbldf <- tbl_df(df)
col.names <- colnames(df)
categories <- c("7alawa","lazeez","mashy","za7ma","mafeesh amal")
```

View Sample Row
```
crawl_date			Fri Feb  5 17:23:57 UTC 2016
ad/aid				2538
ad/bgcl				#003768
ad/bgcls			#0069aa
ad/fncl				#FFFFFF
ad/fncls			#FFFFFF
ad/lid				1001
ad/logo				http://www.bey2ollak.com/downloads/logos/Pepsi_SA7EL.png
ad/logo2x			http://www.bey2ollak.com/downloads/logos/Pepsi_SA7EL@2x.png
ad/logoAndroidS		http://www.bey2ollak.com/downloads/logos/Pepsi_SA7EL_ANDROID_S.png
ad/logoAndroidH		http://www.bey2ollak.com/downloads/logos/Pepsi_SA7EL_ANDROID_H.png
ad/cm				?????? ?????? ???????? ?????????? ?????????? ???????????? ???? ???????? ???????? #??????_????????
ad/url				http://youtu.be/aNeqShdgupY
ad/g				1
rd/nm				Makram 3ebeid;Autostrad To Mostafa ElNa7as
rd/ri				678
rd/stid				3
rd/hr				1
rd/mn				12
rd/new				1
rd/img				NA
rd/cl				#E6E6E6
rd/strq				1
rd/cmrq				0
rd/rp/nm			Tahany_Eyad
rd/rp/fullnm		Tahany Eyad
rd/rp/hr			18
rd/rp/mn			38
rd/rp/stid			2
rd/rp/cm			lazeez
rd/rp/cmid			9300046
rd/rp/rpImg			NA
rd/rp/img			NA
rd/rp/type			0
```

```{r}
## Removing advertisement Columns
ad.cols <- which(grepl("ad", col.names))
```

```{r}
## Checking if image columns are useful
img.cols <- which(grepl("img", col.names, ignore.case = T))
```
```{r}
summary(df$rd.img)
#Percentage of NAs
sum(is.na(df$rd.img))/length(df$rd.img)
```

```{r}
summary(df$rd.rp.img)
sum(is.na(df$rd.rp.img))/length(df$rd.rp.img)
```

```{r}
summary(df$rd.rp.rpImg)
sum(is.na(df$rd.rp.rpImg))/length(df$rd.rp.rpImg)
```

```{r}
#Check if rd.rp.type is useful
rd.rp.type <- which(col.names == "rd.rp.type")
summary(df$rd.rp.type)
```

```{r}
#Removing Image Columns, road reporter type, reporter fullname
#road reporter name and road reporter full name explain pretty much the same thing 

#Checking if road columns are useful
#View(unique(df[,c("rd.nm","rd.ri","rd.stid","rd.strq","rd.cmrq")]))
#looking at rd.nm and rd.stid, looks like there are multiple rd.stid for the same road, which is useless, so we will remove this column
#relationship between road name and rd.ri
#View(unique(df[,c("rd.nm","rd.ri")]))
#sa7rawi cairo to alex and other roads exist twice

# Looking at what rd.strq, rd.cmrq
# View the unique values | or may plot the names on the x axis and the value on the y axis
# Notice that some high ways have a value or 0,1 but only in city ways have a value of 0
# Let's see why some high ways might have 2 values
#s <- df %>% select(rd.nm, rd.ri, rd.stid,rd.strq,rd.cmrq,rd.rp.cm)  %>% filter(rd.ri == 307 | rd.ri == 243)
# So when the comments are related to in city status it has a value of 0, and 1 otherwise

# The variable sr.cmrq has no apparent relationshp to a specific kind of data, lets 'drop it



rd.rp.fullnm <- which(col.names == "rd.rp.fullnm")
#road color is the same for all roads, so useless
rd.cl <- which(col.names == "rd.cl")

init.df <- df[-c(img.cols, ad.cols, rd.rp.type, rd.rp.fullnm, rd.cl)]
init.df <- init.df[-c(4:7,9,15)]
```
View example Row
```
rd/nm				Makram 3ebeid;Autostrad To Mostafa ElNa7as
rd/ri				678
rd/stid				3
rd/hr				1
rd/mn				12
rd/new				1
rd/cl				#E6E6E6
rd/strq				1
rd/cmrq				0
rd/rp/nm			Tahany_Eyad
rd/rp/fullnm		Tahany Eyad
rd/rp/hr			18
rd/rp/mn			38
rd/rp/stid			2
rd/rp/cm			lazeez
rd/rp/cmid			9300046
rd/rp/type			0
```

```{r}
#splitting rd.nm column into Region,From,To
scratch.df <- init.df %>% separate(rd.nm, c("Region", "From", "To"), sep="(( To )|;)", remove = TRUE)

# Create apropriate date out of crawl date
crawl.date <- scratch.df$crawl_date
crawl.date <- crawl.date %>% str_split("(\\s)+|:")
crawl.date <- crawl.date %>% sapply(FUN = concat.as.date)
crawl.date <- ymd_hms(crawl.date)
scratch.df <- scratch.df %>% mutate(crawl_date=crawl.date)

# Subtracting as time (rd.rp.hr, rd.rp,mn) from the crawl date to get the actual date of the pots
scratch.df <- scratch.df %>% mutate(crawl_date=
                              crawl_date %m-% hours(rd.rp.hr)
                            %m-% minutes(rd.rp.mn))
# Drop rd.rp.hr, rd.rp.mn
scratch.df <- scratch.df %>% select(-c(rd.rp.mn,rd.rp.hr))

# Give Columns meaningful names
colnames(scratch.df) <- c("date","region","from","to","road_id","is_city_road","reporter","tag","comment")


```


```{r labeling_by2ollakgps}
# A look at the reporter name indicates that there are some posts posted by b2yolalk gps, let's separate them, and add a new column category 
scratch.df <- scratch.df %>% mutate(category = ifelse(reporter == "bey2ollakgps", "report", NA))

```

```{r}
#Now lets see the percentages of data we have
#gpy <- scratch.df %>% group_by(category)
#c <- summarize(gpy, percentage = n()/nrow(scratch.df))
#x <- c[,1][[1]]
#y <- c[,2][[1]]
#x[is.na(x)] = "Unknown"
#g <- ggplot(data = c, aes(x,y,fill = x))
#g+geom_bar(stat="identity")
```


```{r looking_at_comments_column}
#Explorign the column rd.rp.cm
#We know there are already five categories (7alawa, lazeez, report, za7ma, mfesh amal, so2al)
#Having a look at what other comments say
#other.comments <- scratch.df[!(scratch.df$comment %in% categories),]
#Other patterns may appear such as 7adsa,khatar,3otl, key wrods embedded in text
```

```{r mining_comments}
# It is still clear we still have a lot of data that is unknown, about 18% of the data.
# Now we try to compensate this problem
# Look at the data points with NA category
#head(scratch.df %>% filter(is.na(category)) %>% arrange(desc(comment)))
# we observe the occurence of some other non formal keywords, such as "zeft", "foll", "w7esh", "khara", "zebala", "gamed". Also exists some other variations of the key word "za7ma" such as "zahma" and the occurence of multiple 'a' chatacters in between
#also many recrods contains people asking questions, which were not caught before in our previous trick rp.rp.stid == 6, and there are people talking to each other,usually starting their sentence with @ let's catch them and put them in a category "interactions"
ptrn.7alawa <- c("[7h]e*a*la*wa*",
                 "pe*rfe*ct", 
                 "fol+",
                 "3a*sa*l",
                 "فل",
                 "حلو",
                 "حلاو(ة|ه)",
                 "لوز",
                 "عسل")

ptrn.lazeez <- c("la+z[ie]+z", 
                 "la+t[ie]+f", 
                 "ko*w*[ei]+s",
                 "ta+m+a+m",
                 "ga+m[ei]*[dl]", 
                 "nice",
                 "za+r[ie]+f",
                 "goo+d",
                 "ظري*ف",
                 "جا*مد",
                 "جمي*ل",
                 "تما*م",
                 "لزي*ز",
                 "كويس",
                 "لذي*ذ")

ptrn.mashy <- c("ma*sh[iy]+a*",
                "sha*[(gh)8(3')]a+l",
                "ما*شي",
                "شغا*ل",
                "معقو*ل",
                "يعن[يى]")

ptrn.z7ma <- c("z.*[7h]a?ma+",
               "w.*7.*sh",
               "ba*d",
               "slow",
                "ب.*ط.*[ءئ]",
               "ز*ح*م(ة|ه)",
               "وحشة*",
               "ك.*د.*س",
               "و.*س.*خ",
               "زحا*م")

ptrn.mfesh_aml <- c("ma*fe*sh\\s2?a*ma*l",
                    "(kh|5)a*ra+",
                    "z.*ft+",
                    "z[aei]*ba*la*",
                    "wa*2*a*e*fa*",
                    "ga*[7h][ei]+m",
                    "avo*i*d",
                    "blocke?d?",
                    "2*a*ra*f",
                    "ba*[(sh)t]e*[32]",
                    "[7h]a*ra+m+",
                    "sa*wa+d",
                    "زفت*",
                    "خر*[اهة]ة",
                    "م*ني+لة؟",
                    "قر+ف+",
                    "جحي*م",
                    "وا*قف",
                    "مفيش\\sامل",
                    "زبا*ل(ه|ة)",
                    "م*ني*ل",
                    "م*قفو*ل",
                    "حرا*م",
                    "سوا*د")

ptrn.question <- c("(.)*\\?+$",
                   "up(\\s)?d8*a*t*e*s?",
                   "n[aei]*za+m",
                   "(a|eh)\\se?l\\ska*la*m",
                   "g[ae]*de*d",
                   "a[kh|5]ba*r",
                   "ne*ws",
                   "[اأ]خبا*ر",
                   "نظا*م",
                   "كلا*م",
                   "جدي+د",
                   "سبب",
                   "ع.*ر.*ف",
                   "في*ن",
                   ".*؟+$",
                   "اي[هة]*ه")

ptrn.interaction <- c("^@.")

ptrn.khatar <- c("ra*da+r",
                 "khatar",
                 "la*gna+",
                 "ka*me+n",
                 "كمي*ن",
                 "لجن(ه|ة)",
                 "را*دا*ر",
                 "خطر")

ptrn.7adsa <- c("7a*dsa*",
                "accident",
                "karsa",
                "حا*دث(ه|ة)*",
                "خا*بط")

ptrn.3otl <- c("3[oaie]*t[aie]*l",
               "[ea]sla*[7h]a*t",
               "اصلاحات",
               "ا*عطا*ل")

ptrn.list <- list(
                  "question" = ptrn.question,
                  "interaction" = ptrn.interaction, 
                  "7adsa" = ptrn.7adsa, 
                  "3otl" = ptrn.3otl,
                  "khatar" = ptrn.khatar, 
        				  "7alawa" = ptrn.7alawa, 
                  "lazeez" = ptrn.lazeez, 
                  "mashy" = ptrn.mashy, 
                  "z7ma" = ptrn.z7ma, 
                  "mfesh_aml" = ptrn.mfesh_aml
        				  )

ptrn.vector <- sapply(ptrn.list, paste, collapse = "|")
ptrn.names <- names(ptrn.list)

unk <- scratch.df %>% filter(is.na(category))
unk.size <- nrow(unk)
print(unk.size)

has.category <- with(scratch.df,sapply(comment, get.category, patterns = ptrn.vector, names = ptrn.names))
scratch.df <- scratch.df %>% mutate(category = ifelse(is.na(category)&has.category!=-1,has.category,category))

unk2 <- scratch.df %>% filter(is.na(category))
unk2.size <- nrow(unk2)
print(unk2.size)

# Let's now check the percentage of unknown data we still have
unk2.size/nrow(scratch.df)
# Less than 10%, satisfying to some extent

```

```{r plotting_tag_cat_scatter_plot}
#Now, a quick look at the new category column and column tag raises the urge to question whether these two columns are related

#See summary of variables
tag.c <- scratch.df$tag
cat.c <- scratch.df$category

tag.c <- as.factor(tag.c)
cat.c <- as.factor(cat.c)

summary(tag.c)
summary(cat.c)


#Plot
g <- ggplot(mapping = aes(cat.c,tag.c,col=tag.c))
g+geom_point() +geom_jitter()

# It seems like there is something going on here, but is is not really obvious in the plot due to the different frequencies of each label/tag, let's try to see which category mined from the text relates to which tag
tag.category <- with(scratch.df,table(tag,category))
tag.category <- scale(tag.category)
levelplot(tag.category, col.regions= colorpanel(16,"moccasin","tomato2"))
# It is clear how the relation goes between the tag and the category, we may use this later to discover more things

```

```{r}
#Looks like there is indeed a relationship between both columns, we can infer the following parings:
# 1 --> 7alawa
# 2 --> lazeez
# 3 --> mashy
# 4 --> za7ma
# 5 --> mfeesh amal
# 6 --> ??
# 7 --> khatar
# 8 --> 7adsa (One very interesting observation is that both the number 8 and 5 relate to 7adsa, this is logical because 7adsa always results in mfeesh amal)
# 9 --> 3otl
# Let's further try to categorize the data, it is observable that number 6 is associated with people making enquiries about the road status, and that there are many data points generated by reports from by2ollakgps service, let's set the category column for both of these

#scratch.df <- scratch.df %>% mutate(category = ifelse(tag == 6, "question", category))

# and plot again
stid <- as.factor(scratch.df$tag)
cat <- as.factor(scratch.df$category)

#Plot
#g <- ggplot(mapping = aes(cat,stid,col=stid))
#g+geom_point() +geom_jitter()

```


```{r}
#Now after we have almost done pruning the useless columsn and adding some usefuel ones, we notice that our table contains multiple values:
#     1. Reports by by2ollakgps
#     2. People asking questions about the condition of the road
#     3. People sending messages to specfic people; starting with @
#     4. People giving their opinion of in-city roads; those with in_city column of        value 1
#     5. People giving their opinion of high-way roads; those with in_city column of       value 0
#     6. data with unknown category 
```

```{r}
#The data now seems 
#Posts by By2ollak
#by2ollaks <- which(grepl("bey2ollakgps", init.df$reporter,ignore.case = T))
#by2ollakdf <- init.df[by2ollaks,]
#othersdf <- init.df[-by2ollaks,]
##Percentage of posts by By2ollak
#nrow(by2ollakdf)/nrow(df)


