
```{r}
rm(list = ls())
setwd("E:/GUC/10th/Introduction to data science/Project 1")
# Loading libraries
require(dplyr)
require(tidyr)
require(stringr)
require(ggplot2)
```
```{r}
# Loading data
df <- read.csv("all-semi-unique.csv")
df <- df %>% mutate(rd.rp.cm = as.character(rd.rp.cm))

# Checking for duplicates of df$rd.rp.cmid
duplicates <- duplicated(df$rd.rp.cmid)
n.duplicates <- sum(duplicates)
percent.duplicates <- n.duplicates/dim(df)[1]
print(percent.duplicates)
# About 65% of the data is duplicated
old.df <- df
df <- df[!duplicates,]
#tbldf <- tbl_df(df)
col.names <- colnames(df)
categories <- c("7alawa","lazeez","mashy","za7ma","mafeesh amal")
```

View Sample Row
```
crawl_date			Fri Feb  5 17:23:57 UTC 2016
ad/aid				2538
ad/bgcl				#003768
ad/bgcls			#0069aa
ad/fncl				#FFFFFF
ad/fncls			#FFFFFF
ad/lid				1001
ad/logo				http://www.bey2ollak.com/downloads/logos/Pepsi_SA7EL.png
ad/logo2x			http://www.bey2ollak.com/downloads/logos/Pepsi_SA7EL@2x.png
ad/logoAndroidS		http://www.bey2ollak.com/downloads/logos/Pepsi_SA7EL_ANDROID_S.png
ad/logoAndroidH		http://www.bey2ollak.com/downloads/logos/Pepsi_SA7EL_ANDROID_H.png
ad/cm				?????? ?????? ???????? ?????????? ?????????? ???????????? ???? ???????? ???????? #??????_????????
ad/url				http://youtu.be/aNeqShdgupY
ad/g				1
rd/nm				Makram 3ebeid;Autostrad To Mostafa ElNa7as
rd/ri				678
rd/stid				3
rd/hr				1
rd/mn				12
rd/new				1
rd/img				NA
rd/cl				#E6E6E6
rd/strq				1
rd/cmrq				0
rd/rp/nm			Tahany_Eyad
rd/rp/fullnm		Tahany Eyad
rd/rp/hr			18
rd/rp/mn			38
rd/rp/stid			2
rd/rp/cm			lazeez
rd/rp/cmid			9300046
rd/rp/rpImg			NA
rd/rp/img			NA
rd/rp/type			0
```

```{r}
## Removing advertisement Columns
ad.cols <- which(grepl("ad", col.names))
```
```{r}
for(i in 1:5){print(i)}
```

```{r}
## Checking if image columns are useful
img.cols <- which(grepl("img", col.names, ignore.case = T))
```
```{r}
summary(df$rd.img)
#Percentage of NAs
sum(is.na(df$rd.img))/length(df$rd.img)
```

```{r}
summary(df$rd.rp.img)
sum(is.na(df$rd.rp.img))/length(df$rd.rp.img)
```

```{r}
summary(df$rd.rp.rpImg)
sum(is.na(df$rd.rp.rpImg))/length(df$rd.rp.rpImg)
```

```{r}
#Check if rd.rp.type is useful
rd.rp.type <- which(col.names == "rd.rp.type")
summary(df$rd.rp.type)
```

```{r}
#Removing Image Columns, crawl date, road reporter type, reporter fullname
#road reporter name and road reporter full name explain pretty much the same thing 
rd.rp.fullnm <- which(col.names == "rd.rp.fullnm")
#road color is the same for all roads, so useless
rd.cl <- which(col.names == "rd.cl")
newdf <- df[-c(img.cols, ad.cols, rd.rp.type, rd.rp.fullnm, rd.cl)]
```
View example Row
```
rd/nm				Makram 3ebeid;Autostrad To Mostafa ElNa7as
rd/ri				678
rd/stid				3
rd/hr				1
rd/mn				12
rd/new				1
rd/cl				#E6E6E6
rd/strq				1
rd/cmrq				0
rd/rp/nm			Tahany_Eyad
rd/rp/fullnm		Tahany Eyad
rd/rp/hr			18
rd/rp/mn			38
rd/rp/stid			2
rd/rp/cm			lazeez
rd/rp/cmid			9300046
rd/rp/type			0
```

```{r}
#splitting rd.nm column into Region,From,To
newdf2 <- newdf %>% separate(rd.nm, c("Region", "From", "To"), sep="(( To )|;)", remove = TRUE)
```

```{r}
#Explorign the column rd.rp.cm
#We know there are already five categories (7alawa, lazeez, report, za7ma, mfesh amal, so2al)
#Having a look at what other comments say
other.comments <- newdf2[!(newdf2$rd.rp.cm %in% categories),]
#Other patterns may appear such as 7adsa,khatar,3otl
other.categories <- c("7adsa","khatar","3otl","question","report")
#let's add a column category to specify the category of each comment by perofrming a niive match to the string inside the comment to one of the known categories so far.
newdf2 <- newdf2 %>% mutate(category = str_extract(rd.rp.cm, paste(c(categories, other.categories), collapse = "|")))

```

```{r}
#Now, a quick look at the new category column and column rd.rp.stid raises the urge to question whether these two columns are related

#See summary of variables
stid <- newdf2$rd.rp.stid
cat <- newdf2$category

summary(stid)
summary(cat)

stid <- as.factor(stid)
cat <- as.factor(cat)

#Plot
g <- ggplot(mapping = aes(cat,stid,col=stid))
g+geom_point() +geom_jitter()
```

```{r}
#Looks like there is indeed a relationship between both columns, we can infer the following parings:
# 1 --> 7alawa
# 2 --> lazeez
# 3 --> mashy
# 4 --> za7ma
# 5 --> mfeesh amal
# 6 --> ??
# 7 --> khatar
# 8 --> 7adsa (One very interesting observation is that both the number 7 and 5 relate to 7adsa, this is logical because 7adsa always results in mfeesh amal)
# 9 --> 3otl
# Let's further try to categorize the data, it is observable that number 6 is associated with people making enquiries about the road status, and that there are many data points generated by reports from by2ollakgps service, let's set the category column for both of these
newdf2 <- newdf2 %>% mutate(category = ifelse(rd.rp.stid == 6, "question", category))
newdf2 <- newdf2 %>% mutate(category = ifelse(rd.rp.nm == "bey2ollakgps", "report", category))
# and plot again
stid <- as.factor(newdf2$rd.rp.stid)
cat <- as.factor(newdf2$category)

#Plot
g <- ggplot(mapping = aes(cat,stid,col=stid))
g+geom_point() +geom_jitter()

```

```{r}
#Now lets see the percentages of data we have
gpy <- newdf2 %>% group_by(category)
c <- summarize(gpy, percentage = n()/nrow(newdf2))
x <- c[,1][[1]]
y <- c[,1][[2]]
qplot(x,y)

```{r}
#Posts by By2ollak
by2ollaks <- which(grepl("bey2ollakgps", newdf$rd.rp.nm,ignore.case = T))
by2ollakdf <- newdf[by2ollaks,]
othersdf <- newdf[-by2ollaks,]
##Percentage of posts by By2ollak
nrow(by2ollakdf)/nrow(df)
```

